Neos:
  Neos:
    Ui:
      resources:
        javascript:
          Shel.Neos:ColorPickerEditor:
            resource: resource://Shel.Neos.ColorPicker/Public/ColorPickerEditor/Plugin.js

      frontendConfiguration:
        'Shel.Neos:ColorPickerEditor':
          # `mode` can be one of "rgba", "hsla", "hex"
          mode: 'rgba'
